name: mate-kd
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10

  # PyTorch ecosystem
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8

  # Core scientific computing
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.1

  # Visualization
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - plotly=5.15.0

  # Image processing
  - opencv=4.7.1
  - pillow=9.5.0

  # Machine learning utilities
  - scikit-learn=1.3.0
  - tqdm=4.65.0

  # Configuration and utilities
  - pyyaml=6.0
  - click=8.1.6

  # Jupyter ecosystem
  - jupyter=1.0.0
  - jupyterlab=4.0.3
  - ipywidgets=8.0.7

  # Development tools
  - black=23.7.0
  - flake8=6.0.0
  - pytest=7.4.0

  # Additional dependencies via pip
  - pip=23.2.1
  - pip:
    - grad-cam==1.4.8
    - tensorboard==2.13.0
    - wandb==0.15.8
    - torchinfo==1.8.0
    - timm==0.9.2
    - einops==0.6.1
    - uv==0.1.32 